//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistaghost.VISTAGHOST.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vistaghost.VISTAGHOST.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vistaghost.About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Addacomment_8818 {
            get {
                object obj = ResourceManager.GetObject("Addacomment_8818", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorContextMenus.CodeWindow.AddComments.
        /// </summary>
        internal static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment tags succeeded.
        /// </summary>
        internal static string AddCommentSuccess {
            get {
                return ResourceManager.GetString("AddCommentSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vistaghost.ChangeInfo.
        /// </summary>
        internal static string ChangeInfo {
            get {
                return ResourceManager.GetString("ChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vistaghost.Configurations.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorContextMenus.CodeWindow.CopyPrototype.
        /// </summary>
        internal static string CopyPrototype {
            get {
                return ResourceManager.GetString("CopyPrototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorContextMenus.CodeWindow.CountLinesofCode.
        /// </summary>
        internal static string CountLOC {
            get {
                return ResourceManager.GetString("CountLOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorContextMenus.CodeWindow.DeleteComments.
        /// </summary>
        internal static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All comments have been deleted.
        /// </summary>
        internal static string DeleteCommentSuccess {
            get {
                return ResourceManager.GetString("DeleteCommentSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings can not be exported. Please try again.
        /// </summary>
        internal static string ExportFailedMessage {
            get {
                return ResourceManager.GetString("ExportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings has been exported succeeded.
        /// </summary>
        internal static string ExportSuccessMessage {
            get {
                return ResourceManager.GetString("ExportSuccessMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FunctionHS {
            get {
                object obj = ResourceManager.GetObject("FunctionHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vistaghost.HistoryViewer.
        /// </summary>
        internal static string HistoryViewer {
            get {
                return ResourceManager.GetString("HistoryViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vistaghost.ImportandExportSettings.
        /// </summary>
        internal static string ImportExport {
            get {
                return ResourceManager.GetString("ImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import new settings succeeded.
        /// </summary>
        internal static string ImportSettingsSuccess {
            get {
                return ResourceManager.GetString("ImportSettingsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Log&gt;
        ///  &lt;VGHistory&gt;
        ///
        ///  &lt;/VGHistory&gt;
        ///  &lt;VGError&gt;
        ///    
        ///  &lt;/VGError&gt;
        ///&lt;/Log&gt;
        ///.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make function header failed.
        /// </summary>
        internal static string MakeHeaderFaield {
            get {
                return ResourceManager.GetString("MakeHeaderFaield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make function header succeeded.
        /// </summary>
        internal static string MakeHeaderSuccess {
            get {
                return ResourceManager.GetString("MakeHeaderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vistaghost.CreateMultiHeader.
        /// </summary>
        internal static string MultiHeader {
            get {
                return ResourceManager.GetString("MultiHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text selection.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PrintPreviewHS {
            get {
                object obj = ResourceManager.GetObject("PrintPreviewHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search2 {
            get {
                object obj = ResourceManager.GetObject("search2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SearchFunc {
            get {
                object obj = ResourceManager.GetObject("SearchFunc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorContextMenus.CodeWindow.MakeFunctionHeader.
        /// </summary>
        internal static string SingleHeader {
            get {
                return ResourceManager.GetString("SingleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vistaghost Results.
        /// </summary>
        internal static string VistaghostWindowTitle {
            get {
                return ResourceManager.GetString("VistaghostWindowTitle", resourceCulture);
            }
        }
    }
}
